[package]
name = "microservice-rust"
version = "0.1.0"
authors = ["KentaKudo <yd37574@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
tower-grpc-build = { git = "https://github.com/tower-rs/tower-grpc" }
